config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'index' => 'welcome#index'
  get 'posts/new' => 'posts#new'
  post 'posts' => 'posts#create'
  get 'posts/:id' => 'posts#show', as: 'post'
  get 'posts/:id/edit' => 'posts#edit', as: 'post_edit'
  patch 'posts/:id' => 'posts#update'
  delete 'posts/:id' => 'posts#destroy'
  delete 'comments/:id' => 'comments#destroy', as: 'comments'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title,
    :presence => true, :length => { :minimum => 5 }
  validates :text,
    :presence => true, :length => { :minimum => 20 }
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with :name => "dhh", :password => "secret", :only => :destroy

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with :name => "dhh", :password => "secret", :expection => [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    if post.save
      redirect_to :root
    else
      flash[:errors] = post.errors.full_messages
      redirect_back fallback_location: root_path
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to :root
    else
      flash[:errors] = post.errors.full_messages
      redirect_back fallback_location: root_path
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to :action => :index
  end

private
  def post_params
    params.require(:post).permit(:title, :text)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<% content_for(:title, "Comments") %>

<% @post.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
    <%= link_to "Delete Comment", [comment.post, comment],
    data: { method: :delete, confirm: "Are you sure?" } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |e| %>
    <p><%= e %></p>
  <% end %>
<% end %>

<%= form_for(@post) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<% content_for(:title, "Edit") %>

<h1>Editing post</h1>

<%= render partial: 'posts/form' %>

<%= link_to 'Go Back', :action => :index %>

app/views/posts/index.html.erb
<% content_for(:title, "Posts") %>

<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
  <tr>
  <% @posts.each do |post| %>
    <td><%= post.title %></td>
    <td><%= post.text %></td>
    <td>
      <%= link_to "Show", :action => :show, :id => post.id %>
      <%= link_to "Edit", :action => :edit, :id => post.id %>
      <%= link_to "Delete Post", post_path(post.id),
     data: { method: :delete, confirm: "Are you sure?" } %>
   </td>
  </tr>
  <% end %>
</table>

<%= link_to "Create new post", :action => :new %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render partial: 'posts/form' %>

<%= link_to 'Back', :action => :index %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p>
  <strong>Text:</strong><br />
  <%= @post.text %>
</p>

<h2>Comments</h2>
<%= render partial: 'comments/comment' %>

<h2>Add a comment:</h2>
<%= render partial: 'comments/form' %>

<%= link_to "Edit Post", edit_post_path(@post) %> |
<%= link_to "Back to Posts", posts_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>

<p>Find me in app/views/welcome/inde.html.erb</p>

<%= link_to "My Blog", :controller => "posts" %>